security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    # clé providers : Comment on va récupérer les users et les authentification
    providers:
        users: #on peut mettre à la place in_database
            entity:
                class: 'App\Entity\User' #classe qui sert à l'auth
                property: username 
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #chaque personna est considérée comme anonyme
            anonymous: true
            logout:
                path: logout
                target: home
            # activate different ways to authenticate
            # http_basic: true
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

            form_login:
                #chemin utilisé pour faire de la vérif (nom de la route)
                check_path: login


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
        
