vich_uploader:
    db_driver: orm

    mappings:
        property_image: #nom du mapping
            uri_prefix: /images/properties #dossier dans lequel on envoie nos images
            upload_destination: '%kernel.project_dir%/public/images/properties' #où je souhaite envoyer mes fichier
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
